[tool.poetry]
name = "geocoding"
version = "0.1.0"
description = ""
authors = ["rvcristiand <rvcristiand@unal.edu.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
geopy = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
